In [12]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [14]:
df = pd.read_excel(r"C:\Users\KHARENIUM\Desktop\adresler_guncel.xlsx") # replace with your own file path

In [16]:
df.head()

,Kütüphane Adı,İlçe Adı,Açılış Yılı,Adres,Telefon,Çalışma Saatleri,Çalışma Günleri,Enlem,Boylam
0,Atatürk Kitaplığı (Merkez Kütüphane),Beyoğlu,1981,"Miralay Şefik Bey Sok. No: 6 Taksim, Beyoğlu - İstanbul",0 (212) 249 95 65\n0 (212) 249 09 45,09:00-22:00,Hergün,41.038842,28.988988
1,Kadın Eserleri Kütüphanesi,Fatih,1990,Fener Mah. Mürselpaşa Cad. No: 8 Haliç - Fatih - İstanbul,0 (212) 534 95 50,09:00-17:00,Pazartesi-Cuma,41.030775,28.950385
2,Barış Manço Kütüphanesi,Esenler,1999,Birlik Mah. 857. Sok. No: 2 Atışalanı Köyiçi Esenler - İstanbul,0 (212) 430 30 23 \n0 (212) 430 42 03,09:00-17:00,Pazartesi-Cumartrsi,41.053897,28.873117
3,Eyüp Sultan Kütüphanesi,Eyüpsultan,1999,Merkez Mah. Kızıl Mescit Sok. No: 14 Eyüp - İstanbul,0 (212) 417 33 96\nDahili:663808,09:00-17:00,Pazartesi-Cuma,41.046762,28.936101
4,Ahmet Süheyl Ünver Kütüphanesi,Ümraniye,2002,"Alemdağ Cad. Haldun Alagaş Spor Kompleksi, Ümraniye - İstanbul",0 (216) 634 44 22,09:00-21:00,Hergün,41.024960,29.104736

In [18]:
df = df[["Kütüphane Adı","Enlem","Boylam"]]
df.head()

                          Kütüphane Adı      Enlem     Boylam
0  Atatürk Kitaplığı (Merkez Kütüphane)  41.038842  28.988988
1            Kadın Eserleri Kütüphanesi  41.030775  28.950385
2               Barış Manço Kütüphanesi  41.053897  28.873117
3               Eyüp Sultan Kütüphanesi  41.046762  28.936101
4        Ahmet Süheyl Ünver Kütüphanesi  41.024960  29.104736

In [20]:
import pandas as pd

output_file = "adreslerr.json" 


df.to_json(output_file, orient='records', force_ascii=False, indent=4)

print(f"Excel dosyası JSON formatına dönüştürüldü ve {output_file} olarak kaydedildi.")

Excel dosyası JSON formatına dönüştürüldü ve adreslerr.json olarak kaydedildi.